# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "usbhid" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" "ec_sys" ];
  boot.extraModprobeConfig = ''
    options ec_sys write_support=1
    options nvidia NVreg_DynamicPowerManagement=0x02
  '';
  boot.extraModulePackages = [ ];
  boot.kernelParams = [
    "acpi_rev_override=1"
    "acpi_osi=Linux"
    "nouveau.modeset=0"
    "pcie_aspm=off"
    "drm.vblankoffdelay=1"
    "scsi_mod.use_blk_mq=1"
    "nouveau.runpm=0"
    "mem_sleep_default=deep"
  ];

  boot.binfmt.emulatedSystems = [
    "aarch64-linux"
  ];

  boot.initrd.luks.devices.crypted = {
    device = "/dev/disk/by-uuid/63640f50-26db-4e09-82ee-92e18b93e62e";
  };

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/4a010770-8fa6-4e11-ab70-530791fac16b";
      fsType = "ext4";
    };
  fileSystems."/home" =
    {
      device = "/dev/disk/by-uuid/27e78500-e9d5-4a36-a881-be9f90fcafce";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/B362-9D39";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/2b179543-e2ba-4957-bef5-8dec53849431"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp60s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp61s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
