# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config
, pkgs
, lib
, modulesPath
, ...
}:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ehci_pci"
    "usbhid"
    "nvme"
    "usb_storage"
    "sd_mod"
    "aesni_intel"
    "cryptd"
  ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" "msi-ec" ];

  boot.extraModulePackages = with config.boot.kernelPackages; [
    msi-ec
  ];

  boot.blacklistedKernelModules = [
    "nvidia"
    "nvidia_uvm"
    "nvidia_drm"
    "nvidia_modeset"
  ];

  boot.kernelParams = [
    "acpi_rev_override=1"
    "acpi_osi=Linux"
    "pcie_aspm=off"
    "drm.vblankoffdelay=1"
    "scsi_mod.use_blk_mq=1"
    "mem_sleep_default=deep"
  ];

  boot.binfmt.emulatedSystems = [
    "aarch64-linux"
  ];

  boot.initrd.systemd.enable = true;


  boot.initrd.luks.devices.cryptroot = {
    device = "/dev/disk/by-uuid/3436694d-6b2b-4a4b-a25b-52b43f582e1a";
    allowDiscards = true;
    keyFileSize = 4096;
    keyFile = "/dev/disk/by-id/usb-General_USB_Flash_Disk_04NCZ3G8Y7ERGZRJ-0:0";
    keyFileTimeout = 3;
    bypassWorkqueues = true;
  };

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/7082afa7-b2d9-477e-9971-8b1d6b173f5a";
      fsType = "ext4";
    };

  fileSystems."/home" =
    {
      device = "/dev/disk/by-uuid/056a57bb-d810-4baa-919c-6d0a624130cf";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/FCBC-10DE";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [
      { device = "/dev/disk/by-uuid/18c9673f-0d9b-4dae-bfac-e0b703470512"; }
    ];


  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  hardware.acpilight.enable = true;

  hardware = {

    openrazer.enable = true;

    graphics = {
      extraPackages = with pkgs; [
        mesa
        mesa.drivers
      ];
      enable = true;
    };
    nvidia = {
      open = true;
      prime = {
        sync.enable = true;
        offload.enable = false;
        intelBusId = "PCI:0:2:0";
        nvidiaBusId = "PCI:1:0:0";
      };
      powerManagement.enable = true;
    };

  };
}
