" Disable vi compat to avoid issue
set nocompatible

" file detection
filetype on

" enable plugins
filetype plugin on

" load indent file
filetype indent on

" Highlight syntax
syntax on

set number
set relativenumber
set cc=80
set tabstop=4
set shiftwidth=4
set expandtab

set hlsearch

set wildmenu
set wildmode=list:longest

" set cursorline

" key remaps
nnoremap + :m -2<CR>
nnoremap - :m +1<CR>

" windows and tabs remaps
nnoremap <leader>t :tabe %<CR>:tabprev<CR>:q<CR>:tabnext<CR>

inoremap jj <esc>

" autocomplete stuff
inoremap ( ()<Left>
inoremap { {}<Left>
inoremap [ []<Left>


function! CompleteBrackets(brack)
	let l:currentChar = getline(".")[col(".") - 1]
	if a:brack == l:currentChar
		return <Right>
	else
		return brack
	endif
endfunction


" color schemes
colorscheme molokai


" STATUS LINE ------------------------------------------- {{{

set ruler
set rulerformat=%55(%{strftime('%a\ %b\ %e\ %I:%M\ %p')}\ %5l,%-6(%c%V%)\ %P%)

set statusline=

set statusline+=\ %F\ %M\ %Y

set statusline+=%=

set statusline+=\ lines:\ %l-%L(%p%%),\ cols:\ %c\ 

set laststatus=2

" }}}
